name: Deploy to Server

on:
  push:
    branches:
      - main # Adjust this branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      - name: Copy to Server
        run: |
          scp -r -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }} ./dist/* ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.SSH_PATH }}
